name: NodeJS

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.10.0 ]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          pnpm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/demo # The folder the action should deploy.
          clean: true # Automatically remove old files from the deployment branch
          repository-name: 'CosticaPuntaru/fracsi' # Replace with your username and repository
          token: ${{ secrets.GITHUB_TOKEN }} # A deployment token. You can use `${{ secrets.GITHUB_TOKEN }}` for this.
